services:
  backend:
    build: backend
    volumes:
      - "./backend:/var/www/html"
  frontend:
    build: frontend
    volumes:
      - "./frontend:/app"
  balancer:
    build: balancer
    ports:
      - "80:80"